### ISSUE TITLE
Missing chalk module in package.json

### ISSUE THREAD

**Issue by dkaraush** [Pecacheu/dualshock#3]
When I ran `npm install dualshock` and did `require('dualshock')`, i have seen:
```
$ node
> ds=require('dualshock')
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```
In `package.json` there is nothing about `chalk`. Please, add it to file.

**Comment by Pecacheu** [comment]
That should do it
